Lab5
katekaa/IU5-Frontend-2021 pull request #5
Opened 2021-03-26 21:18 UTC by katekaa

2021-03-30 18:56 UTC, youraavdeev commented
конфликты

2021-03-30 18:56 UTC, youraavdeev commented
куча изменений

2021-03-30 19:02 UTC, youraavdeev requested changes

2021-03-30 19:02 UTC, youraavdeev commented on lab5/3.js
> +    return f.bind(context);
ты же понимаешь что задача не использовать настоящий bind

2021-04-04 20:48 UTC, katekaa commented on lab5/3.js
> +    return f.bind(context);
переделала 3ю задачу, решила конфликты

2021-04-06 14:42 UTC, merged